title = "" # 楽曲のタイトル
artist = "" # 楽曲のアーティスト
scoreDesigner = "" # 譜面制作者
stageTitle = "" # ステージ名
difficulty = "normal" # 難易度 easy | normal | hard
musicFilePath = "hoge.mp3" # 必須
bpm = 155 # 必須
beatPerMeasure = 4 # 必須 1小節あたりの拍数
musicVolume = 1.0 # 音楽の音量
soundVolume = 1.0 # 効果音の音量

[notes]
defaultIntervalBeat = 6 # デフォルトのintervalBeat (地面に固定されたノーツが画面横サイズ分を移動するのにかかる拍数)(背景の移動速度もこれを参照する)
firstBeatTimePos = 0 # 1拍目の時間(秒)
rawCSV = '''
#B Melody
45m+4b,kick
45m+4b,crash
45m+4.5b,kick
45m+4.5b,hihat
46m+1b,snare
46m+1.5b,hihat
46m+2b,kick
46m+2.5b,hihat
46m+3b,snare
46m+3.5b,kick
46m+3.5b,hihat
46m+4.5b,kick
46m+.4.5b,hihat
47m+1b,snare
47m+1.5b,hihat
47m+2b,kick
47m+2.5b,kick
47m+2.5b,hiahat
47m+3b,snare
47m+3b,hihat
47m+3.5b,kick
47m+3.5b,hihat
47m+3.75b,snare
47m+4b,kick
47m+4b,crash
47m+4.5b,kick
47m+4.5b,hihat
48m+1b,snare
48m+1.5b,hiahat
48m+2b,kick
48m+2.5b,hihat
48m+3b,snare
48m+3.5b,kick
48m+3.5b,hihat
48m+4.5b,kick
48m+4.5b,hihat
49m+1b,snare
49m+1.5b,hihat
49m+2b,kick
49m+2.5b,kick
49m+2.5b,hihat
49m+3b,snare
49m+3.5b,kick
49m+3.5b,hihat
49m+3.75b,snare
49m+4b,kick
49m+4b,crash
49m+4.5b,kick
49m+4.5b,hihat
50m+1b,snare
50m+1.5b,hihat
50m+2b,kick
50m+2.5b,hihat
50m+3b,snare
50m+3.5b,kick
50m+3.5b,hihat
50m+4.5b,kick
50m+4.5b,hihat
51m+1b,snare
51m+1.5b,kick
51m+1.5b,hihat
51m+2b,kick
51m+2b,hihat
51m+2.5b,kick
51m+3b,snare
51m+3b,hihat
51m+3.5b,kick
51m+3.75b,snare
51m+4b,kick
51m+4b,hihat
51m+4b,crash
52m+1b,snare
52m+1b,hihat
52m+1.5b,kick
52m+1.5b,crash
52m+2.5b,snare
52m+3b,kick
52m+3b,hihat
52m+3b,crash
52m+4b,snare
52m+4.5b,kick
52m+4.5b,crash
53m+1b,snare
53m+1b,hihat
53m+1.5b,hiahat
53m+2b,kick
53m+2.5b,kick
53m+2.5b,hihat
53m+3b,snare
53m+3.5b,kick
53m+3.5b,hihat
53m+3.75b,snare
53m+4b,kick
53m+4b,hihat
54m+1b,kick
54m+1b,hihat
54m+2b,kick
54m+2b,hihat
54m+2.5b,snare
54m+3b,kick
54m+3b,hihat
54m+4b,kick
54m+4b,hihat
55m+1b,kick
55m+1b,hihat
55m+2b,kick
55m+2b,hihat
55m+2.5b,snare
55m+2.5b,hihat
55m+3b,kick
55m+3b,hihat
55m+3.25b,snare
55m+3.5b,snare
55m+3.75b,snare
55m+4b,hihat
55m+4b,crash
55m+4.5b,snare
56m+1b,kick
56m+1b,hihat
56m+1b,crash
56m+1.5b,snare
56m+1.75b,snare
56m+2b,kick
56m+2b,hihat
56m+2b,crash
56m+2.5b,snare
56m+3b,kick
56m+3b,hihat
56m+3b,crash
56m+3.5b,snare
56m+4b,kick
56m+4b,hihat
56m+4b,crash
56m+4.5b,snare
57m+1b,kick
57m+1b,hihat
57m+1.5b,snare
57m+2b,kick
57m+2b,hihat
57m+2.5b,snare
57m+3b,snare
57m+3.25b,snare
57m+3.5b,kick
57m+3.5b,hihat
57m+4b,snare
57m+4.5b,kick
57m+4.5b,hihat
58m+1.5b,kick
58m+1.5b,hihat
58m+2b,snare
58m+2.5b,kick
58m+2.5b,hihat
58m+3.5b,kick
58m+3.5b,hihat
58m+4b,kick
58m+4b,snare
58m+4.5b,hihat
59m+1b,kick
59m+1.5b,kick
59m+1.5b,hihat
59m+2b,snare
59m+2.5b,kick
59m+2.5b,hihat
59m+2.75b,snare
59m+3b,snare
'''